#!/bin/sh

# MARK: - Config Path
CONFIG_PLIST_PATH=""

if [ "$CI_XCODE_SCHEME" == "Armony" ]; then
    CONFIG_PLIST_PATH='../Armony/Resources/Configs/ReleaseConfiguration.xcconfig'
else
    CONFIG_PLIST_PATH='../Armony/Resources/Configs/DebugConfiguration.xcconfig'
fi

# MARK: - FIREBASE CONFIGURATION
echo "FIREBASE_CLIENT_ID = ${FIREBASE_CLIENT_ID}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_REVERSED_CLIENT_ID = ${FIREBASE_REVERSED_CLIENT_ID}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_API_KEY = ${FIREBASE_API_KEY}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_GCM_SENDER_ID = ${FIREBASE_GCM_SENDER_ID}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_PLIST_VERSION = ${FIREBASE_PLIST_VERSION}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_BUNDLE_ID = ${FIREBASE_BUNDLE_ID}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_PROJECT_ID = ${FIREBASE_PROJECT_ID}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_STORAGE_BUCKET = ${FIREBASE_STORAGE_BUCKET}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_IS_ADS_ENABLED = ${FIREBASE_IS_ADS_ENABLED}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_IS_ANALYTICS_ENABLED = ${FIREBASE_IS_ANALYTICS_ENABLED}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_IS_APPINVITE_ENABLED = ${FIREBASE_IS_APPINVITE_ENABLED}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_IS_GCM_ENABLED = ${FIREBASE_IS_GCM_ENABLED}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_IS_SIGNIN_ENABLED = ${FIREBASE_IS_SIGNIN_ENABLED}" >> $CONFIG_PLIST_PATH
echo "FIREBASE_GOOGLE_APP_ID = ${FIREBASE_GOOGLE_APP_ID}" >> $CONFIG_PLIST_PATH

# MARK: - FACEBOOK CONFIGURATION
echo "FACEBOOK_APP_ID = ${FACEBOOK_APP_ID}" >> $CONFIG_PLIST_PATH
echo "FACEBOOK_CLIENT_TOKEN = ${FACEBOOK_CLIENT_TOKEN}" >> $CONFIG_PLIST_PATH

# MARK: - MIXPANEL CONFIGURATION
echo "MIXPANEL_TOKEN = ${MIXPANEL_TOKEN}" >> $CONFIG_PLIST_PATH

# MARK: - ADJUST CONFIGURATION
echo "ADJUST_TOKEN = ${ADJUST_TOKEN}" >> $CONFIG_PLIST_PATH

# MARK: - GOOGLE PLIST PATH

INFO_PLIST_PATH=""
if [ "$CI_XCODE_SCHEME" == "Armony" ]; then
    INFO_PLIST_PATH='../Armony/Resources/Firebase/GoogleService-Info.plist'
else
    INFO_PLIST_PATH='../Armony/Resources/Firebase/GoogleService-Info-Debug.plist'
fi

# MARK: - POPULATE GOOGLE PLIST
/usr/libexec/PlistBuddy -c "Set :CLIENT_ID ${FIREBASE_CLIENT_ID}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :REVERSED_CLIENT_ID ${FIREBASE_REVERSED_CLIENT_ID}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :API_KEY ${FIREBASE_API_KEY}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :GCM_SENDER_ID ${FIREBASE_GCM_SENDER_ID}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :PLIST_VERSION ${FIREBASE_PLIST_VERSION}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :BUNDLE_ID ${FIREBASE_BUNDLE_ID}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :PROJECT_ID ${FIREBASE_PROJECT_ID}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :STORAGE_BUCKET ${FIREBASE_STORAGE_BUCKET}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :IS_ADS_ENABLED ${FIREBASE_IS_ADS_ENABLED}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :IS_ANALYTICS_ENABLED ${FIREBASE_IS_ANALYTICS_ENABLED}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :IS_APPINVITE_ENABLED ${FIREBASE_IS_APPINVITE_ENABLED}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :IS_GCM_ENABLED ${FIREBASE_IS_GCM_ENABLED}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :IS_SIGNIN_ENABLED ${FIREBASE_IS_SIGNIN_ENABLED}" $INFO_PLIST_PATH
/usr/libexec/PlistBuddy -c "Set :GOOGLE_APP_ID ${FIREBASE_GOOGLE_APP_ID}" $INFO_PLIST_PATH
